name: Sync Fork

on:
  workflow_dispatch:
  schedule:
  - cron: "0 1 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sync and merge upstream repository with your current repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with:
          # URL of gitHub public upstream repo
          upstream_repo: https://github.com/blackmatrix7/ios_rule_script
          # Branch to merge from upstream (defaults to downstream branch)
          upstream_branch: master
          # Branch to merge into downstream
          downstream_branch: master
          # GitHub Bot token
          token: ${{secrets.GITHUB_TOKEN}}
